config/routes.rb
Rails.application.routes.draw do
  resources :tournaments
  resources :engines
  root "pages#home"
	resources :round_two_participants, only: [:create, :destroy]

	resources :round_three_participants, only: [:create, :destroy]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/engine.rb
class Engine < ApplicationRecord
  has_many :participants
  has_many :tournaments, through: :participants
	has_many :round_two_participants

	has_many :round_three_participants
  has_many :round_three_tournaments, through: :round_three_participants, source: :tournament

end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: %i[ show edit update destroy ]

  # GET /engines or /engines.json
  def index
    @engines = Engine.all
  end

  # GET /engines/1 or /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines or /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: "Engine was successfully created." }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1 or /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: "Engine was successfully updated." }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1 or /engines/1.json
  def destroy
    @engine.destroy!

    respond_to do |format|
      format.html { redirect_to engines_path, status: :see_other, notice: "Engine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def engine_params
      params.expect(engine: [ :name ])
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_engine.html.erb
<div id="<%= dom_id engine %>">
  <p>
    <strong>Name:</strong>
    <%= engine.name %>
  </p>

</div>

app/views/engines/_form.html.erb
<%= form_with(model: engine) do |form| %>
  <% if engine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
        <% engine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<% content_for :title, "Editing engine" %>

<h1>Editing engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Show this engine", @engine %> |
  <%= link_to "Back to engines", engines_path %>
</div>

app/views/engines/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Engines" %>

<h1>Engines</h1>

<div id="engines">
  <% @engines.each do |engine| %>
    <%= render engine %>
    <p>
      <%= link_to "Show this engine", engine %>
    </p>
  <% end %>
</div>

<%= link_to "New engine", new_engine_path %>

app/views/engines/new.html.erb
<% content_for :title, "New engine" %>

<h1>New engine</h1>

<%= render "form", engine: @engine %>

<br>

<div>
  <%= link_to "Back to engines", engines_path %>
</div>

app/views/engines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @engine %>

<div>
  <%= link_to "Edit this engine", edit_engine_path(@engine) %> |
  <%= link_to "Back to engines", engines_path %>

  <%= button_to "Destroy this engine", @engine, method: :delete %>
</div>